openapi: 3.0.1
info:
  version: "3.00"
  title: List handler
  description: "To save a bunch of stuff for later."
paths:
  /getItems:
    get:
      summary: To get a list of all saved items.
      responses:
        200:
          description: All the currently saved items.
          content:
            text/plain:
              schema:
                type: string
                description: comma delimted string with pipe delimited values for amt|item
                example: 2|oranges,12|apples,3|lemons
        500:
          description: Error
          content:
            text/plain:
              schema:
                type: string
                example: "Something went terribly wrong."

  /newItem:
    post:
      summary: To add a new item to your list.
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              description: pip delimited string for amt|item
              example: 2|white peaches
      responses:
        200:
          description: Everything went ok!
          content:
            text/plain:
              schema:
                type: string
                example: OK
        500:
          description: Error
          content:
            text/plain:
              schema:
                type: string
                example: "Something went terribly wrong."
